- name: enhancement
  color: 2ECC71
  description: Feature work that improves the automation portfolio
- name: bug
  color: E74C3C
  description: Defect impacting expected behaviour
- name: chore
  color: 95A5A6
  description: Maintenance or cleanup tasks
- name: docs
  color: 3498DB
  description: Documentation-only changes
- name: infra
  color: 9B59B6
  description: Infrastructure, pipelines, or environments
- name: security
  color: F39C12
  description: Security fixes or hardening
- name: good first issue
  color: A3E4D7
  description: Friendly starting point for new contributors
